name: 'Build and deploy storybook on PR'
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, closed, synchronize]

jobs:
  storybook-preview:
    runs-on: ubuntu-latest
    name: Deploy storybook
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
        if: github.event.action != 'closed'

      - name: Install dependencies
        run: npm ci
        if: github.event.action != 'closed'

      - name: build -> deploy storybook
        uses: Sauloxd/review-apps@v2.0.0
        with:
          branch: 'gh-pages'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          apps: |
            {
              "storybook": {
                "build": "npm run build-storybook",
                "dist": "storybook-static"
              }
            } 